@base_url = https://localhost:44384

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImp0aSI6ImY0ZWE2MjU3LWIxYjItNGRjMi05MDJiLWIzNjFiMWE2NmU3ZCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NDI2Mzg0MTAsImlzcyI6InlvdXJkb21haW4uY29tIiwiYXVkIjoieW91cmRvbWFpbi5jb20ifQ.f0-jxhhk4pJcEwtEaAObWuc5_yFYdoWAepD4m2j-7wU


POST {{base_url}}/api/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password"
}

###
GET {{base_url}}/api/customers
Authorization: Bearer {{token}}

###

@id=1
GET {{base_url}}/api/customers/{{id}}
Authorization: Bearer {{token}}
###
