@base_url = https://localhost:44384

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImp0aSI6IjYzZmM4N2JkLTA2ZjMtNDhiMy1hNjRkLWM4ZmVkN2NlYzIwOCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NDI1OTU1NzgsImlzcyI6InlvdXJkb21haW4uY29tIiwiYXVkIjoieW91cmRvbWFpbi5jb20ifQ.togfe1a-B3ZcVyHFpMjtZL4eBXwueQXCfnsfPKrguec


POST {{base_url}}/api/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password"
}

###
GET {{base_url}}/api/customers
Authorization: Bearer {{token}}

###

@id=1
GET {{base_url}}/api/customers/{{id}}
Authorization: Bearer {{token}}
###
